### PR TITLE
Added first person controller

### PR DESCRIPTION
**Pull request by TimNekk**
_Do not pay attention to branch name  😕_ 

# MASSIVE UPDATE (not really)

The previous beautiful code for moving around by @Yanulio was insane! ❤️ 
But unfortunately I have to use completely different approach, <s>copied</s> inspired from this [vid](https://www.youtube.com/watch?v=_QajrabyTJc).  

## Changes

- Added player blob with camera on top
- Added some shitty code for running fast and rotating rapidly
- Added shinny af playground for messing around with movement
- Added gravity to take away the powers of God from player blob

### CODE REVIEW

**Comment by TimNekk** [comment]
Going to rework input system

**Comment by TimNekk** [comment]
Implemented new [**Unity Input System**](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.4/manual/index.html) for:
- Moving (via _WASD_ and _Arrows_)
- Looking (via _MouseDelta_)

Works kind of the same, but way more elegant! 😎

**Comment by TimNekk** [comment]
## Jumping Introduced

- Press `Spacebar` to **Jump**
- Hold `Spacebar` to **BunnyHop**

## Preview

**Review by Yanulio — APPROVED** [review]
You did a fantastic job! Everything works perfectly 😎😎😎

**Pull request merged**
